language: node_js
cache:
    directories:
        - node_modules
node_js:
  - "9"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install: make stamp-npm
script: BROWSERS=Firefox make check
sudo: false
