dist: bionic
addons:
  chrome: stable
services:
  - xvfb
language: node_js
cache:
    directories:
        - node_modules
node_js:
  - "10"
install: make stamp-npm
script: BROWSERS=Firefox KARMA_ARGS=--single-run make check
sudo: false
